### ISSUE TITLE
[feature request]

### ISSUE THREAD

**Issue by picollo-24** [Element-Re/fu-roll-enhancements#1]
Add option to auto spend MP on features, and possibly allow it to spend variable amount of MP.

Example: Dances cost 10 MP, but when you danced previous turn, you only spend 5 MP per dance.

**Comment by Element-Re** [comment]
Thank you for the suggestion. This is primarily a UI and/or documentation issue that's on my list, but for now both requests are technically possible with the "Show Auto Spend Dialog" keybind — Control by default, though there were some issues with the defaults at some point - you can check it under the "Configure Controls" settings menu.
![image](https://github.com/user-attachments/assets/cbac49ad-41fd-4df4-9705-4d90e9730e59)
Holding the keybind while clicking on any character sheet item lets you modify the auto spend settings for the item even if the Auto Spend settings don't show up on the item's sheet. You can press "Update and Spend" to persist your settings, or just "Spend" to make changes to the current roll only.

EDIT: Also I just pushed an update that fixes the keybind localization strings. You should be able to grab it through the module update feature in the foundry setup page.

**Comment by Element-Re** [comment]
As the wiki has been updated to document using dialog usage, including using the auto spend dialog to make one-off changes to  costs, I am marking this as closed.
