### ISSUE TITLE
The module's update problem

### ISSUE THREAD

**Issue by Vesselchuck** [Element-Re/fu-roll-enhancements#2]
The module cannot be updated due to the lack of some releases thing:
![image](https://github.com/user-attachments/assets/144f8891-af4f-4430-801d-cd5ec1773c51)
![image](https://github.com/user-attachments/assets/d27bd9ff-7c2d-45bf-9b70-5d21a2c279a8)

**Comment by Element-Re** [comment]
Thanks for the report, this should be resolved now.
